-- Run this in your Supabase SQL Editor

-- 1. Logs Table
create table logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  name text,
  value int,
  type text, -- 'food', 'exercise', 'water'
  timestamp bigint,
  date_string text
);

-- 2. Settings Table
create table settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  daily_goal int default 2000,
  water_goal int default 8,
  theme text default 'light',
  unique (user_id) -- Ensure one settings row per user
);

-- 3. History Table
create table history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  date text,
  calories int,
  water int,
  unique (user_id, date)
);

-- Enable RLS
alter table logs enable row level security;
alter table settings enable row level security;
alter table history enable row level security;

-- Create Policies (Using simplified 'for all' but ensure user_id matches)
create policy "Users can manage their own logs" on logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage their own settings" on settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage their own history" on history
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
